// OPS Dashboard Home — summary cards showing business metrics at a glance.
// Client Component — fetches stats from /api/ops/stats after mount.

"use client";

import { useState, useEffect } from "react";
import { 
  Users, TrendingUp, FileText, Trophy, Star, Clock, Loader2
} from "lucide-react";

type Stats = {
  total_leads: number;
  avg_score: string;
  new_leads: number;
  contacted: number;
  proposals_sent: number;
  won: number;
  lost: number;
  high_score_leads: number;
  new_this_week: number;
};

function StatCard({ 
  label, value, icon: Icon, description, accent = false
}: { 
  label: string; value: string | number; icon: any;
  description?: string; accent?: boolean;
}) {
  return (
    <div className={`rounded-xl border p-6 ${accent ? 'border-primary/30 bg-primary/5' : 'border-border bg-card'}`}>
      <div className="flex items-center justify-between mb-4">
        <span className="text-sm font-medium text-muted-foreground">{label}</span>
        <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${accent ? 'bg-primary/10' : 'bg-secondary'}`}>
          <Icon className={`w-4 h-4 ${accent ? 'text-primary' : 'text-muted-foreground'}`} />
        </div>
      </div>
      <p className="text-3xl font-bold font-display">{value ?? '—'}</p>
      {description && (
        <p className="text-xs text-muted-foreground mt-1">{description}</p>
      )}
    </div>
  );
}

export default function OpsDashboard() {
  const [stats, setStats] = useState<Stats | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/ops/stats')
      .then(res => res.json())
      .then(data => { setStats(data); setLoading(false); })
      .catch(() => setLoading(false));
  }, []);

  return (
    <div>
      <div className="mb-8">
        <h1 className="font-display text-2xl font-bold">Dashboard</h1>
        <p className="text-muted-foreground mt-1">
          Welcome back, Samuel. Here's AngaCore Labs at a glance.
        </p>
      </div>

      {loading ? (
        <div className="flex items-center justify-center py-20">
          <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
        </div>
      ) : !stats ? (
        <p className="text-muted-foreground">Failed to load stats.</p>
      ) : (
        <>
          <div className="grid grid-cols-2 lg:grid-cols-3 gap-4 mb-8">
            <StatCard label="Total Leads" value={stats.total_leads} icon={Users} description="Discovered by ORION" />
            <StatCard label="Avg Score" value={stats.avg_score} icon={TrendingUp} description="Out of 10" accent />
            <StatCard label="High Value" value={stats.high_score_leads} icon={Star} description="Scored 9 or above" />
            <StatCard label="New This Week" value={stats.new_this_week} icon={Clock} description="Added in last 7 days" />
            <StatCard label="Proposals Sent" value={stats.proposals_sent} icon={FileText} description="Generated by NAMI" />
            <StatCard label="Won" value={stats.won} icon={Trophy} description="Closed deals" accent={stats.won > 0} />
          </div>

          <div className="border border-border rounded-xl p-6 bg-card">
            <h2 className="font-display font-semibold mb-4">Pipeline Breakdown</h2>
            <div className="space-y-3">
              {[
                { label: 'New', value: stats.new_leads, color: 'bg-blue-500' },
                { label: 'Contacted', value: stats.contacted, color: 'bg-purple-500' },
                { label: 'Proposal Sent', value: stats.proposals_sent, color: 'bg-orange-500' },
                { label: 'Won', value: stats.won, color: 'bg-green-500' },
                { label: 'Lost', value: stats.lost, color: 'bg-red-500' },
              ].map(({ label, value, color }) => (
                <div key={label} className="flex items-center gap-3">
                  <span className="text-sm text-muted-foreground w-32">{label}</span>
                  <div className="flex-1 bg-secondary rounded-full h-2">
                    <div
                      className={`${color} h-2 rounded-full transition-all`}
                      style={{ width: stats.total_leads > 0 ? `${(value / stats.total_leads) * 100}%` : '0%' }}
                    />
                  </div>
                  <span className="text-sm font-medium w-8 text-right">{value}</span>
                </div>
              ))}
            </div>
          </div>
        </>
      )}
    </div>
  );
}