// OPS Dashboard Home — summary cards showing business metrics at a glance.
// Fetches stats from PostgreSQL via /api/ops/stats.
// Server Component — data fetched at request time, no client-side JS needed.

import { 
  Users, 
  TrendingUp, 
  FileText, 
  Trophy,
  Star,
  Clock
} from "lucide-react";
import { Pool } from 'pg';

// Direct database connection — faster than HTTP self-call
const pool = new Pool({
  host: process.env.DB_HOST || 'angacore_db',
  port: parseInt(process.env.DB_PORT || '5432'),
  database: process.env.DB_NAME || 'angacore',
  user: process.env.DB_USER || 'postgres',
  password: process.env.DB_PASSWORD,
});

async function getStats() {
  try {
    const result = await pool.query(`
      SELECT
        COUNT(*)::int                                          AS total_leads,
        ROUND(AVG(score)::numeric, 1)                         AS avg_score,
        COUNT(*) FILTER (WHERE status = 'new')::int           AS new_leads,
        COUNT(*) FILTER (WHERE status = 'contacted')::int     AS contacted,
        COUNT(*) FILTER (WHERE status = 'proposal_sent')::int AS proposals_sent,
        COUNT(*) FILTER (WHERE status = 'won')::int           AS won,
        COUNT(*) FILTER (WHERE status = 'lost')::int          AS lost,
        COUNT(*) FILTER (WHERE score >= 9)::int               AS high_score_leads,
        COUNT(*) FILTER (WHERE created_at >= NOW() - INTERVAL '7 days')::int AS new_this_week
      FROM leads
    `);
    return result.rows[0];
  } catch (error) {
    console.error('Stats error:', error);
    return null;
  }
}

// Stat card component
function StatCard({ 
  label, 
  value, 
  icon: Icon, 
  description,
  accent = false
}: { 
  label: string; 
  value: string | number; 
  icon: any;
  description?: string;
  accent?: boolean;
}) {
  return (
    <div className={`rounded-xl border p-6 ${accent ? 'border-primary/30 bg-primary/5' : 'border-border bg-card'}`}>
      <div className="flex items-center justify-between mb-4">
        <span className="text-sm font-medium text-muted-foreground">{label}</span>
        <div className={`w-8 h-8 rounded-lg flex items-center justify-center ${accent ? 'bg-primary/10' : 'bg-secondary'}`}>
          <Icon className={`w-4 h-4 ${accent ? 'text-primary' : 'text-muted-foreground'}`} />
        </div>
      </div>
      <p className="text-3xl font-bold font-display">{value ?? '—'}</p>
      {description && (
        <p className="text-xs text-muted-foreground mt-1">{description}</p>
      )}
    </div>
  );
}

export default async function OpsDashboard() {
  const stats = await getStats();

  return (
    <div>
      {/* Page header */}
      <div className="mb-8">
        <h1 className="font-display text-2xl font-bold">Dashboard</h1>
        <p className="text-muted-foreground mt-1">
          Welcome back, Samuel. Here's AngaCore Labs at a glance.
        </p>
      </div>

      {/* Stats grid */}
      {!stats || stats.error ? (
        <p className="text-muted-foreground">Failed to load stats. Check database connection.</p>
      ) : (
        <>
          <div className="grid grid-cols-2 lg:grid-cols-3 gap-4 mb-8">
            <StatCard
              label="Total Leads"
              value={stats.total_leads}
              icon={Users}
              description="Discovered by ORION"
            />
            <StatCard
              label="Avg Score"
              value={stats.avg_score}
              icon={TrendingUp}
              description="Out of 10"
              accent={true}
            />
            <StatCard
              label="High Value"
              value={stats.high_score_leads}
              icon={Star}
              description="Scored 9 or above"
            />
            <StatCard
              label="New This Week"
              value={stats.new_this_week}
              icon={Clock}
              description="Added in last 7 days"
            />
            <StatCard
              label="Proposals Sent"
              value={stats.proposals_sent}
              icon={FileText}
              description="Generated by NAMI"
            />
            <StatCard
              label="Won"
              value={stats.won}
              icon={Trophy}
              description="Closed deals"
              accent={stats.won > 0}
            />
          </div>

          {/* Pipeline breakdown */}
          <div className="border border-border rounded-xl p-6 bg-card">
            <h2 className="font-display font-semibold mb-4">Pipeline Breakdown</h2>
            <div className="space-y-3">
              {[
                { label: 'New', value: stats.new_leads, color: 'bg-blue-500' },
                { label: 'Contacted', value: stats.contacted, color: 'bg-purple-500' },
                { label: 'Proposal Sent', value: stats.proposals_sent, color: 'bg-orange-500' },
                { label: 'Won', value: stats.won, color: 'bg-green-500' },
                { label: 'Lost', value: stats.lost, color: 'bg-red-500' },
              ].map(({ label, value, color }) => (
                <div key={label} className="flex items-center gap-3">
                  <span className="text-sm text-muted-foreground w-32">{label}</span>
                  <div className="flex-1 bg-secondary rounded-full h-2">
                    <div
                      className={`${color} h-2 rounded-full transition-all`}
                      style={{ 
                        width: stats.total_leads > 0 
                          ? `${(value / stats.total_leads) * 100}%` 
                          : '0%' 
                      }}
                    />
                  </div>
                  <span className="text-sm font-medium w-8 text-right">{value}</span>
                </div>
              ))}
            </div>
          </div>
        </>
      )}
    </div>
  );
}